[2024-03-23T01:13:19.771+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_team_standings.create_postgres_table scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:13:19.809+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_team_standings.create_postgres_table scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:13:19.810+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-23T01:13:19.842+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-03-21 13:00:00+00:00
[2024-03-23T01:13:19.856+0000] {standard_task_runner.py:60} INFO - Started process 248 to run task
[2024-03-23T01:13:19.864+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_team_standings', 'create_postgres_table', 'scheduled__2024-03-21T13:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/team_stats.py', '--cfg-path', '/tmp/tmp9jzy44m6']
[2024-03-23T01:13:19.868+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask create_postgres_table
[2024-03-23T01:13:19.995+0000] {task_command.py:423} INFO - Running <TaskInstance: get_team_standings.create_postgres_table scheduled__2024-03-21T13:00:00+00:00 [running]> on host e4a45e6f747a
[2024-03-23T01:13:20.257+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmc' AIRFLOW_CTX_DAG_ID='get_team_standings' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T13:00:00+00:00'
[2024-03-23T01:13:20.260+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS team_standings (
                teamname TEXT, conference TEXT, record TEXT, wins INTEGER,
                losses INTEGER, division TEXT, divisionrecord TEXT,
                divisionrank INTEGER, winpct FLOAT, l10 TEXT, ot TEXT,
                currentstreak INTEGER, pointspg FLOAT, opppointspg FLOAT,
                diffpointspg FLOAT
            );
        
[2024-03-23T01:13:20.301+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-03-23T01:13:20.321+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=get_team_standings, task_id=create_postgres_table, execution_date=20240321T130000, start_date=20240323T011319, end_date=20240323T011320
[2024-03-23T01:13:20.340+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 248)
[2024-03-23T01:13:20.365+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-23T01:13:20.426+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-03-23T01:13:20.473+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
